[package]
name = "ue_tudi_analytics"
version = "0.0.0"
edition = "2021"
description = ""

[lib]
crate-type = ["cdylib", "rlib"]

[profile.wasm-debug]
inherits = "dev"
overflow-checks = false
strip = true
panic = "abort"

[profile.wasm-release]
inherits = "release"
overflow-checks = false
strip = true
opt-level = 'z'
codegen-units = 1
panic = "abort"

[profile.wasm-optimized]
inherits = "release"
overflow-checks = false
strip = true
opt-level = 3
codegen-units = 1
panic = "abort"



[dependencies]
## GENERATED DEPENDENCIES
serde =  { version = "1", features = ["std", "derive"]}
sdfg = { version = "0.13" , features=[ "row"]  }
## END OF GENERATED DEPENDENCIES

unreal-tudi-analytics = { path = "../../../../crates/unreal-tudi-analytics" }
serde_json = "1.0.64"
