name: CI

concurrency:
  group: ci-check-%{{ inputs.sdf_version }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      sdf_version:
        required: true
        type: string
      branch:
        type: string

jobs:
    build-and-generate:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          example_path: [
            "primitives/map",
            "primitives/filter",
            "primitives/filter-map",
            "primitives/flat-map",
            "primitives/merge",
            "primitives/regex",
            "primitives/update-state",
            "primitives/split/filter",
            "primitives/split/filter-map",
            "primitives/key-value/input",
            "primitives/key-value/output",
            "primitives/key-value/chained",
            "dataflows-inline/bank-processing",
            "dataflows-inline/car-processing",
            "dataflows-inline/http-callout",
            "dataflows-inline/openai-callout",
            "dataflows-inline/split-sentence",
            "dataflows-inline/word-counter",
            "dataflows-inline/word-probe",
            "dataflows-composed/mask-user-info",
            "dataflows-composed/split-sentence"
          ]
          sdf-version: [
            "${{ inputs.sdf_version }}"
          ]
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            repository: infinyon/stateful-dataflows-examples
            ref: ${{ inputs.branch}}

        - name: Install stable CLI and start Fluvio cluster
          timeout-minutes: 10
          run: |
            curl -fsS https://hub.infinyon.cloud/install/install.sh | bash

        - name: Setup fluvio bin path
          run:  echo "~/.fluvio/bin" >> $GITHUB_PATH

        - name: Setup fvm bin path
          run:  echo "~/.fvm/bin" >> $GITHUB_PATH

        - name: install wasm wasi target
          run: |
            rustup target add wasm32-wasi

        - name: Install SDF version
          run: |
            fvm install ${{ matrix.sdf-version }}

        - name: Run sdf setup
          run: |
            sdf setup

        - name: Run tests
          working-directory: ./${{ matrix.example_path }}
          run: |
            make e2e
