name: CI

concurrency:
  group: ci-check-%{{ inputs.sdf_version }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      sdf_version:
        required: true
        type: string
      branch:
        type: string

jobs:
    build-and-generate:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          example_path: [
            "primitives/custom-serialization/struct/deserialize",
            "primitives/custom-serialization/struct/serialize",
            "primitives/filter",
            "primitives/filter-map",
            "primitives/flat-map",
            "primitives/key-value/input",
            "primitives/key-value/output",
            "primitives/key-value/chained",
            "primitives/map",
            "primitives/merge",
            "primitives/regex",
            "primitives/split/filter",
            "primitives/split/filter-map",
            "primitives/update-state",
            "primitives/sql/cli",
            "primitives/sql/join",
            "dataflows/bank-processing",
            "dataflows/car-processing",
            "dataflows/hackernews-notify",
            "dataflows/helsinki-transit",
            "dataflows/http-callout",
            "dataflows/mask-user-pii",
            "dataflows/mask-user-pii/package-variant",
            "dataflows/openai-callout",
            "dataflows/split-sentence",
            "dataflows/split-sentence/package-variant",
            "dataflows/word-counter",
            "dataflows/word-probe",
          ]
          sdf-version: [
            "${{ inputs.sdf_version }}"
          ]
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            repository: infinyon/stateful-dataflows-examples
            ref: ${{ inputs.branch}}

        - uses: dtolnay/rust-toolchain@stable

        - name: Install stable CLI and start Fluvio cluster
          timeout-minutes: 10
          run: |
            curl -fsS https://hub.infinyon.cloud/install/install.sh | bash

        - name: Setup fluvio bin path
          run:  echo "~/.fluvio/bin" >> $GITHUB_PATH

        - name: Setup fvm bin path
          run:  echo "~/.fvm/bin" >> $GITHUB_PATH

        - name: install wasm wasi target
          run: |
            rustup target add wasm32-wasip1
            rustup target add wasm32-wasip2
            rustup target add wasm32-wasi

        - name: Install SDF version
          run: |
            fvm install ${{ matrix.sdf-version }}

        - name: install fluvio
          run: |
            fluvio cluster start

        - name: Run sdf setup
          run: |
            sdf setup || true

        - name: Run tests
          working-directory: ./${{ matrix.example_path }}
          run: |
            make e2e
